export const CASINO_CATEGORIES: Record<string, string[]> = {
  // Trending: [
  //   'Aviatrix',
  //   'Plinko',
  //   'Funky Time',
  //   'NFT Aviatrix',
  //   'Crazy 777',
  //   'Crazy777',
  //   'Fortune Gems 500',
  //   'Fortune Gems 2',
  //   'Sweet Bonanza',
  //   'Color Game',
  //   'Andar Bahar',
  //   'Teen Patti 20 20',
  //   'Teen Patti 20-20',
  //   'Mines',
  // ],

  // 'Most Played': [
  //   'Aviator',
  //   'Fortune Gems',
  //   'Super Ace',
  //   '7up 7down',
  //   '7 Up & Down Mini',
  //   'Sic BO',
  //   'Card Matka',
  //   'One Card Meter',
  //   'Coin Toss',
  //   'Crazy Time',
  //   'Dragon Tiger',
  //   'Speed Baccarat',
  // ],

  // 'International Casino': [
  //   'Baccarat Live',
  //   'VIP BlackJack',
  //   'VR 29 Card Baccarat',
  //   'AE SEXY',
  //   'SEXYBCRT LOBBY',
  //   'Red Door Roulette',
  //   'Crazy Coin Flip',
  //   'Lightning Storm',
  //   'Mega ball',
  // ],

  // 'Indian Casino': [
  //   '2 Card TeenPatti',
  //   'Two Card Teenpatti',
  //   '20 20 Poker',
  //   'Poker 20-20',
  //   'Auto Roulette',
  //   '6 Player Poker',
  //   'Lucky 7',
  //   'Lottery',
  //   'Dragon Tiger Lion',
  //   'Test Teenpatti',
  // ],

  // 'Live Casino': [
  //   'Crazy Time',
  //   'Mega Wheel',
  //   'Sexy Baccarat',
  //   'SEXYBCRT LOBBY',
  //   'Super Sic Bo',
  //   'Dragon Tiger',
  //   'Teen Patti T20',
  //   'Teen Patti 20-20',
  //   'Speed baccarat',
  //   'Funky Time',
  // ],

  // Table: [
  //   'Number King',
  //   'HILO',
  //   'Call Break',
  //   'Callbreak Quick',
  //   'Rummy',
  //   'Baccarat Deluxe',
  //   '32 Cards',
  //   'Bonus Dice',
  //   'Mini Roulette',
  // ],

  // Slots: [
  //   'Super Ace',
  //   'Fortune Gems 3',
  //   'Callbreak Quick',
  //   'Super Niubi',
  //   'Fruity Bonanza',
  //   'Fortune Dragon',
  //   'Boxing King',
  //   'Fortune Gems',
  // ],

  // Crash: [
  //   'Aviator',
  //   'JetX',
  //   'Aviatix',
  //   'NFT Aviatrix',
  //   'CricketX',
  //   'Plinko Rush',
  //   'Limbo',
  //   'Avia Bet',
  //   'Avia Rush',
  // ],

  Rebel: [
    'Baccarat',
    'Baccarat Knockout',
    'Teen Patti 20-20',
    'One Card One Day',
    'Test Teenpatti',
    'Dragon Tiger',
    'Dragon Tiger Lion',
    'Aviator X',
    'Chicken Drop',
    'Two Card Teenpatti',
  ],
};
